#!/usr/bin/env node
'use strict';

// BG WH \u001b[47m
// BOLD  \u001b[1m
// RED   \u001b[31m
// GREEN \u001b[32m
// RESET \u001b[0m

setTimeout(function() {
    [
			'',
			'\u001b[31mGreenlock and ACME.js v3 are on the way!\u001b[0m',
			'Watch for updates at https://indiegogo.com/at/greenlock',
			''
		]
		.forEach(function(line) {
			console.info(line);
		});
}, 300);

setTimeout(function() {
	// give time to read
}, 1500);
